import Head from "next/head";
import { Montserrat } from "next/font/google";

const inter = Montserrat({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>SkillVine</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="main">Check if login, else redirect to /login</main>
    </>
  );
}
